name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      #
      - name: Install Maven
        run: apt-get update && apt-get install -y maven

      # Skip test database isn't set up yet
      - name: Build JAR
        run: mvn clean install -DskipTests

  #      - name: Upload JAR as artifact
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: bookstore-jar
  #          path: /target/*.jar

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t bookstore .

  deploy:
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use gcloud command-line tool
        run: |
          gcloud auth configure-docker

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy bookstore \
            --image gcr.io/${{ secrets.PROJECT_ID }}/bookstore \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

